# -*- coding: utf-8 -*-
"""Untitled9.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Etd25YUJRtSWq3oFz7Mec3qfV0b_D1S7
"""

import smtplib
import random
import os
from email.mime.text import MIMEText
from datetime import datetime

sender_email = os.getenv("EMAIL")
receiver_email = os.getenv("RECEIVER")
app_password = os.getenv("PASSWORD")

# 🔥 Add your messages here
messages = [
    "I’m sorry for hurting you. I know words don’t fix things instantly, but I mean this sincerely.",
    "I’ve been thinking about what happened, and I’m sorry. You didn’t deserve to feel that way.",
    "I’m sorry for my part in this. I want to understand better and do better.",
    "I care about you, and I’m sorry I made you feel hurt or unheard.",
    "I know I need to respect your space too. I’m sorry, and I’ll listen when you’re ready.",
    "I’m not trying to pressure you. I just want you to know I’m genuinely sorry."
]
subjects = [
    "I’m really sorry",
    "I owe you an apology",
    "Thinking about what happened",
    "I didn’t mean to hurt you",
    "I want to make this right",
    "I’m sorry, sincerely"
]
def send_email():
    current_time = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    # 🎯 Pick random message
    random_message = random.choice(messages)

    body = f"{random_message}\n\nTime: {current_time}"

    msg = MIMEText(body)
    msg['Subject'] = random.choice(subjects)
    msg['From'] = sender_email
    msg['To'] = receiver_email

    with smtplib.SMTP_SSL("smtp.gmail.com", 465) as server:
        server.login(sender_email, app_password)
        server.send_message(msg)

send_email()
